# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b8588ff17b48fe3af64d53a7824fe215de6110e0e4aece5429e78f884009f9f713566b116c9c0e6b2dde00dc49fa1156f9d5f55fa5f20e03562109ca055a9b

test:
  secret_key_base: 3ca332f1913692e96cd381ecc6fa7794cbc784c03d2029e84e9f4c4f5d3cd61b37f16f9bd3339690e73f8f4504c7d4393809398f5c2297e505df4e65524f7dde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
